apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../security/tetragon
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: tetragon
