apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/zammad
  - tailscale-ingress.yaml
patches:
  - path: helm-values-patch.yaml
    target:
      kind: HelmRelease
      name: zammad
