apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: monitoring
data:
  config.yaml: |
    endpoints:
      - name: Vaultwarden
        url: "http://vaultwarden.vaultwarden.svc.cluster.local"
        interval: 20s
        conditions:
          - "[STATUS] == 200"
      
      - name: WikiJS
        url: "http://wikijs.wikijs.svc.cluster.local:3000"
        interval: 20s
        conditions:
          - "[STATUS] == 200"

      - name: Vikunja
        url: "http://vikunja.vikunja.svc.cluster.local:3456"
        interval: 20s
        conditions:
          - "[STATUS] == 200"
