apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
        - name: vikunja
          image: vikunja/vikunja:0.24.6
          ports:
            - containerPort: 3456
          env:
            - name: VIKUNJA_SERVICE_PUBLICURL
              valueFrom:
                configMapKeyRef:
                  name: vikunja-config
                  key: public_url
            - name: VIKUNJA_DATABASE_TYPE
              value: "postgres"
            - name: VIKUNJA_DATABASE_HOST
              value: "vikunja-db-rw"
            - name: VIKUNJA_DATABASE_DATABASE
              value: "vikunja"
            - name: VIKUNJA_DATABASE_USER
              value: "vikunja"
            - name: VIKUNJA_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vikunja-db-app
                  key: password
            - name: VIKUNJA_SERVICE_TIMEZONE
              valueFrom:
                configMapKeyRef:
                  name: vikunja-config
                  key: timezone
          volumeMounts:
            - name: data
              mountPath: /app/vikunja/files
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vikunja-data
