---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCWMYpJa8+/jeD3yF70bacdFpt/886SVJGqEcwpP3JUmVCL3t7ehLySQ2e3QxKswh5mVqMuuDJp9YKULblWx1wdeT8MoeP59KuCYQkzX6rxPYvBDnQEWbMcBCOELg0XgbwrThx9ECkFVqaXCh+OZ24ICmcIgO9qmCDV4KL9pdyQ1evs16tYx5+bP5p8a+LZ5Yd3vGzBnyaV2cbO4EVDz0XCrEQJkF74u2bUHqxZnthcIxKVenyX49Ulcxw57L+Fh4G47WUoM/+KtQT5oXsITbybZKHJNgx5qbF/qiJDUzHYP4p955UktUJ0uNmDEbDLO847dBJYVX1mHtP3n+JhQ5hHKt5QmUxqOrH0tJOmW+H7qt+o9ldAs64y8b4CmBCGcS+3kSP5gcQGi/03qOPHB/Gz2WJUUgHK4TWhqwcHgR3plOgJtt1prD6dyrd9GksWx8HzdwcbYiYjtM1TKKUIrQltx0I9EgsdAJsnXH9bLMZ3GByIG+4raSd4u9xiYKeQ100k/fT8MMBR11ts0xO4gxqqmfTqN2WA4Mgrz6Wc12IV/zxDiYNVS7TmRSRBFXLT3H2sHsd6S6ub1Bb05JeNicsusdoYYcjG+Ej+UwXMqHSpL6UcL06HpCqAOCF94GhyEci7az6lLATPGcoYq9WDvtStFv+NV/NUoS/6AXEpeQUn3H8D1pXHMPSoU69XyRxhEQknKCyMuTlkhqzTRtFntIuzXi1bYqxqWj/s
    admin-user: AgDmoFcKk7wzTHskxB7n/mGOjDAru9ABJSLAPbijLS5ZPIIUepvRIgXEfawgXaTetlJlnSyA6qGC4u/u4bkEmr603BlA6Z5T2CFd9ousYONpgwjg7UFUHfq/8Dfcm5gsuUsN/xTLFDgwl7EE86CNB5cnfyEBkccE/fKDaJKDaE2jKzfj5VjnP8Z4tqQMioh8i41UIjzVJ76pcM1OfcneOQlxBXQYY8EkxJ/5RHIySd3HLejNJlLvmntmT0h+PUrpgZ2ww5CIktKiA1feK9cQZxXs2utXvLcNB5FKCyPNwDc1KkZyJ+sWiIS6xKDndK8jV+n4VZK0Dxv0vpeDKzh0OVz/vFt3D+8NXYyjdYI2IG0nPqde6WIEj3LbpCxZK0dCg69P01SzOfH1NBSC6t8OAxzr8uH7DTTY7VKO1oaKW/CRuib95F1OtZO5vGpQq9UG8RNexxG/LbXstdhItW7zVkoFZibjqtPbi+iV9Acs28det0sfXZhGlcZyGRScBjY/RMVl5zO7q0kX3SaO0BxW3zj2nJS67XITcaLt+V+I8pDlmfm8FKkT6Jqu/P79SNmJ0wciNgUO4G7N22EjmKyODsxGY8C6xXXFCyCwCgSu8mfjmeinrNljiEUq7HLESHM7kLWA4gWxf1yMyD+EAHtNvI0n3487E6Fab91TCh/tLdevhH9bulN/R3ixnsm5OSwuU5CwfYh70Gesqznn5pE=
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
