apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/vaultwarden

configMapGenerator:
  - name: vaultwarden-config
    namespace: vaultwarden
    literals:
      - domain=http://vaultwarden.localhost
      - signups_allowed=false

patches:
  - target:
      kind: Ingress
      name: vaultwarden
    patch: |-
      - op: add
        path: /spec/rules/0/host
        value: vaultwarden.localhost
      - op: add
        path: /spec/tls
        value:
          - hosts:
              - vaultwarden.localhost
            secretName: vaultwarden-tls
  - target:
      kind: Ingress
      name: vaultwarden
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          cert-manager.io/cluster-issuer: letsencrypt-staging
