apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../storage/longhorn/base
  # - dashboard-sealed-secret.yaml
  - tailscale-ingress.yaml
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: longhorn
