apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../kube-prometheus-stack
  - grafana-sealed-secret.yaml
  - tailscale-ingress.yaml
patches:
  - path: helmrelease-patch.yaml
