apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stirling-pdf-tailscale
  namespace: stirling-pdf
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - stirling-pdf.zebra-alewife.ts.net
  rules:
    - host: stirling-pdf.zebra-alewife.ts.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stirling-pdf
                port:
                  number: 8080
