apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/homepage-wordpress
  - wordpress-config-sealed-secret.yaml
  - mysql-sealed-secret.yaml
  - tailscale-ingress.yaml
patchesStrategicMerge:
  - helm-values-patch.yaml
