---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-wordpress-config
  namespace: homepage-wordpress
spec:
  encryptedData:
    values.yaml: AgAXDRhcLhTcMVqunS0gpdOpEt8fnaVURCnYDAaaeF0UVhr5YrHiDUNAkcfEszIvJu/ntiNoTKq6QNw2zjRqe36D1sMOGtN3CKfxzzQoov62llCq+CiLj1faY2iIpB+KPoj21WmPzzcOi+DANulRM6Sd13Bce609Ckr7Kjw+BihT+UpadnTvGZ6+5rWnLfrzMSM7vPKEJ0M7/ERk7zYDmUtaH3o4kAwe2qUkX/kuo9fROE5VfQqclGV2VuUHJq129TOfsjvKoosV1aDE7PXEoCiP5YhI1OnJIejgTqfux89f1KDEAk//Pmdcz6EQNV3ZNenJR3ZpYt+NojNsOLhXxD6wG1/aEE38w3J+G+ZS3kAA3xKoa9bMZonW3WWGNBdelbeMQNCLyr8fDvDBAsq5v87oa7OWpLFxYWwAa+aeO5puExwKjued7MNX1HT4+fQdRo9nP2IIsuLhaJKaIjA+H2TzKI36n02uvb6nW7cv4lpSfZZnhOWNOueVqnfzRFvyvkM7929uxTDBLlDWUvXvFRtxbMHrTry4iKbB/SgUO47EV2CKihlO79k9yUMs8hCULqgiWwJO7zB0naoNxhRc2gKzeQ2CfVuO0DcHBfGF/YxsCCfj281nfZ5ndVyCGVbK5+1kDwD3mg038OnvB6ccdTSdpr3de8KbCdKyTKViLiC1O0OG/d2F3M91ideEUc5jW6s/Dj2hkhtqMYzhm/redlqMuH1vYBZT6nVCpVGDMmp6KQdeCOzMGofcS+NdGEJENCtgZY4q0n3WOrsADRMO6ln3IVMnXaP62a/Gnxjg+ZaYKfOihXc9p27AdlBW6pL4Ya/IlsncKkwvb+W4Rjnjekz2w6x9pv4eilKPVi9rCTpEKoW/eAPTNojsXCGDsSepu85wNZ04ogAkk+WyhMrDgwXJn0Ou
  template:
    metadata:
      name: homepage-wordpress-config
      namespace: homepage-wordpress
    type: Opaque
