apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-wordpress-config
  namespace: homepage-wordpress
spec:
  encryptedData:
    values.yaml: AgAOgZZixFvZMKyFKkKsPv5OQ0Ms+L2DGMEzOsFV09RdYHog253MtsR7T7uDi/n4LpKDRUBi0WH6W8yi8x+ch204aj7G+LJbkzdCeEXPPVYEzoPZ5boJdH6Ddp+h3L3W9RTnXV6vEymjwg8xDC3bJOhHB+KpSslst7P9t/mLpQ4JAzsO7ePkb4rhdl9oKUTyh6y/LUP/mpRrm9n+3qsSwZY1cAc0aXP6aBSggC3QvWCW+Zv+HnNv0JGFC4TtHiFpEvfFf/DVz7UJb3G8FhMdbyd4c4vlXvbw9zv2L3CXfvCbXiQ4i1YAmL5lCeMw+SDv+Q9pf2ZHDuKTYR+CDsuI9iI7BY6gabO45TnHgKFcgfH3S90N9KPRnUuALHNZRx9tg1mwI/D4rBn8yKzI1zTDwPKAmRM7bXl+W2j9HIlIwNyznz2cuWgJJajLplu9NQ6+dims7t4Q7pn0SpRKjshhHH3NBLv7OJqaFLp+S0aVzfLN89isMTRRSNs1SZ3glAvr976n5nyh+wuh2WaS66fRzMyFo/fKVNc1Hcr6QSSUaqLtMRDw5DwVTzlJ5mo/kubdn0/DEdnraxlJSi/nxyQHQcAPpYc0r+U1itzQXyfcK0KFg5QjccXYzHv6iL90YLkVFh1GjRImdsUw7er4f/4/7drNsyD9R1p4mvh7/vega7LwefyNKu6A7h2Vf2hY10bMNM79vgUPRgSXogK2R1PIBheotO4iT4kYjuH60HxscDTgoVl+U0PqDp6AA9dSXXwfkQsEZRMGqA+wmApHEKhy42eE3YDpfVFpxb8ubS1KRgtV4iglRvdeJimX6aiCZjXS2wNrZyfCdRMs/l/HBjItgtudzKintid3bYK/I9ICLOI0fw1Pg2C5zWyH5sPT4eBgnXJsEQGbICfEexIqAmuUI1p7Iveq
  template:
    metadata:
      name: homepage-wordpress-config
      namespace: homepage-wordpress
    type: Opaque
